version: '3.8'

services:
  database:
    image: postgres:15
    container_name: tracker_db
    environment:
      POSTGRES_DB: tracker_db
      POSTGRES_USER: tracker_user
      POSTGRES_PASSWORD: tracker_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tracker_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tracker_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Database=tracker_db;Username=tracker_user;Password=tracker_password
    ports:
      - "5000:8080"
    depends_on:
      - database
    networks:
      - tracker_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tracker_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tracker_network

volumes:
  postgres_data:

networks:
  tracker_network:
    driver: bridge
